### ISSUE TITLE
希望能遵守开源协议

### ISSUE THREAD

**Issue by fordes123** [chengzhongxue/halo-theme-mcnav#1]
你好，
我是 [ITEM](https://github.com/fordes123/ITEM) 仓库的所有者，注意到你在本仓库中直接使用了来自 [ITEM](https://github.com/fordes123/ITEM) 的源代码并移除了有关原作者和原项目的所有信息。

移植工作本是值得称赞的，但同时希望你能遵守原项目 [GPLv3](https://github.com/fordes123/ITEM?tab=GPL-3.0-1-ov-file) 许可证的要求，保留原作者的版权声明和许可信息。

**Comment by chengzhongxue** [comment]
我是对着另外一个人移植的所以没看到原作者的相关信息，等会我就改过来，把你的信息都加上

**Comment by fordes123** [comment]
> 我是对着另外一个人移植的所以没看到原作者的相关信息，等会我就改过来，把你的信息都加上

好的，谢谢你。

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-mcnav/assets/89380218/6e8e610b-6cb4-453a-8255-ed6177ab4020)
这样可以？

**Comment by fordes123** [comment]
> ![image](https://private-user-images.githubusercontent.com/89380218/337137830-6e8e610b-6cb4-453a-8255-ed6177ab4020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTUzNjcsIm5iZiI6MTcxNzY1NTA2NywicGF0aCI6Ii84OTM4MDIxOC8zMzcxMzc4MzAtNmU4ZTYxMGItNmNiNC00NTNhLTgyNTUtZWQ2MTc3YWI0MDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA2MjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTBkMTBlMWFiNWY2OTYxNGNjMGIyZGViNWY2OGIyMDk4ZTFhOTk5YmZjNDNjZDhiZmE2Y2ZmOWI3NjA1NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cyug6URkdgPvuOkb6gM0PFdacuQP0qYal1md2q4MCww) 这样可以？

可以的
